<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PrefecturesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $prefectures = [
            [
                'id' => 1,
                'name' => '北海道',
                'capital' => '札幌市',
                'population' => 5_139_522,
                'area' => 78_420,
                'visited' => true,
            ],
            [
                'id' => 2,
                'name' => '青森県',
                'capital' => '青森市',
                'population' => 1_204_372,
                'area' => 9_645,
                'visited' => true,
            ],
            [
                'id' => 3,
                'name' => '岩手県',
                'capital' => '盛岡市',
                'population' => 1_180_512,
                'area' => 15_275,
                'visited' => false,
            ],
            [
                'id' => 4,
                'name' => '宮城県',
                'capital' => '仙台市',
                'population' => 2_305_596,
                'area' => 7_282,
                'visited' => false,
            ],
            [
                'id' => 5,
                'name' => '秋田県',
                'capital' => '秋田市',
                'population' => 966_311,
                'area' => 11_637,
                'visited' => false,
            ],
            [
                'id' => 6,
                'name' => '山形県',
                'capital' => '山形市',
                'population' => 1_077_551,
                'area' => 9_323,
                'visited' => false,
            ],
            [
                'id' => 7,
                'name' => '福島県',
                'capital' => '福島市',
                'population' => 1_869_538,
                'area' => 13_783,
                'visited' => true,
            ],
            [
                'id' => 8,
                'name' => '茨城県',
                'capital' => '水戸市',
                'population' => 2_875_963,
                'area' => 6_408,
                'visited' => true,
            ],
            [
                'id' => 9,
                'name' => '栃木県',
                'capital' => '宇都宮市',
                'population' => 1_943_886,
                'area' => 6_408,
                'visited' => true,
            ],
            [
                'id' => 10,
                'name' => '群馬県',
                'capital' => '前橋市',
                'population' => 1_939_626,
                'area' => 6_406,
                'visited' => true,
            ],
            [
                'id' => 11,
                'name' => '埼玉県',
                'capital' => 'さいたま市',
                'population' => 7_338_610,
                'area' => 37_955,
                'visited' => true,
            ],
            [
                'id' => 12,
                'name' => '千葉県',
                'capital' => '千葉市',
                'population' => 6_242_562,
                'area' => 5_157,
                'visited' => true,
            ],
            [
                'id' => 13,
                'name' => '東京都',
                'capital' => '東京',
                'population' => 13_929_280,
                'area' => 2_187,
                'visited' => true,
            ],
            [
                'id' => 14,
                'name' => '神奈川県',
                'capital' => '横浜市',
                'population' => 9_126_901,
                'area' => 2_415,
                'visited' => true,
            ],
            [
                'id' => 15,
                'name' => '新潟県',
                'capital' => '新潟市',
                'population' => 2_285_856,
                'area' => 12_582,
                'visited' => true,
            ],
            [
                'id' => 16,
                'name' => '富山県',
                'capital' => '富山市',
                'population' => 1_035_238,
                'area' => 4_247,
                'visited' => false,
            ],
            [
                'id' => 17,
                'name' => '石川県',
                'capital' => '金沢市',
                'population' => 1_154_097,
                'area' => 4_185,
                'visited' => true,
            ],
            [
                'id' => 18,
                'name' => '福井県',
                'capital' => '福井市',
                'population' => 767_787,
                'area' => 4_190,
                'visited' => false,
            ],
            [
                'id' => 19,
                'name' => '山梨県',
                'capital' => '甲府市',
                'population' => 817_242,
                'area' => 4_465,
                'visited' => true,
            ],
            [
                'id' => 20,
                'name' => '長野県',
                'capital' => '長野市',
                'population' => 2_052_493,
                'area' => 13_561,
                'visited' => true,
            ],
            [
                'id' => 21,
                'name' => '岐阜県',
                'capital' => '岐阜市',
                'population' => 2_000_821,
                'area' => 10_621,
                'visited' => true,
            ],
            [
                'id' => 22,
                'name' => '静岡県',
                'capital' => '静岡市',
                'population' => 3_701_801,
                'area' => 7_777,
                'visited' => true,
            ],
            [
                'id' => 23,
                'name' => '愛知県',
                'capital' => '名古屋市',
                'population' => 7_552_873,
                'area' => 5_172,
                'visited' => false,
            ],
            [
                'id' => 24,
                'name' => '三重県',
                'capital' => '津市',
                'population' => 1_815_790,
                'area' => 5_776,
                'visited' => false,
            ],
            [
                'id' => 25,
                'name' => '滋賀県',
                'capital' => '大津市',
                'population' => 1_412_916,
                'area' => 4_017,
                'visited' => false,
            ],
            [
                'id' => 26,
                'name' => '京都府',
                'capital' => '京都市',
                'population' => 2_582_413,
                'area' => 4_612,
                'visited' => true,
            ],
            [
                'id' => 27,
                'name' => '大阪府',
                'capital' => '大阪市',
                'population' => 8_839_238,
                'area' => 1_905,
                'visited' => true,
            ],
            [
                'id' => 28,
                'name' => '兵庫県',
                'capital' => '神戸市',
                'population' => 5_469_762,
                'area' => 8_400,
                'visited' => true,
            ],
            [
                'id' => 29,
                'name' => '奈良県',
                'capital' => '奈良市',
                'population' => 1_348_926,
                'area' => 3_691,
                'visited' => true,
            ],
            [
                'id' => 30,
                'name' => '和歌山県',
                'capital' => '和歌山市',
                'population' => 963_579,
                'area' => 4_725,
                'visited' => false,
            ],
            [
                'id' => 31,
                'name' => '鳥取県',
                'capital' => '鳥取市',
                'population' => 555_793,
                'area' => 3_507,
                'visited' => false,
            ],
            [
                'id' => 32,
                'name' => '島根県',
                'capital' => '松江市',
                'population' => 673_847,
                'area' => 7_098,
                'visited' => false,
            ],
            [
                'id' => 33,
                'name' => '岡山県',
                'capital' => '岡山市',
                'population' => 1_914_190,
                'area' => 7_115,
                'visited' => false,
            ],
            [
                'id' => 34,
                'name' => '広島県',
                'capital' => '広島市',
                'population' => 2_846_145,
                'area' => 8_479,
                'visited' => false,
            ],
            [
                'id' => 35,
                'name' => '山口県',
                'capital' => '山口市',
                'population' => 1_348_926,
                'area' => 6_112,
                'visited' => false,
            ],
            [
                'id' => 36,
                'name' => '徳島県',
                'capital' => '徳島市',
                'population' => 728_633,
                'area' => 4_146,
                'visited' => false,
            ],
            [
                'id' => 37,
                'name' => '香川県',
                'capital' => '高松市',
                'population' => 956_069,
                'area' => 1_876,
                'visited' => false,
            ],
            [
                'id' => 38,
                'name' => '愛媛県',
                'capital' => '松山市',
                'population' => 1_342_011,
                'area' => 5_676,
                'visited' => false,
            ],
            [
                'id' => 39,
                'name' => '高知県',
                'capital' => '高知市',
                'population' => 728_276,
                'area' => 7_103,
                'visited' => false,
            ],
            [
                'id' => 40,
                'name' => '福岡県',
                'capital' => '福岡市',
                'population' => 5_103_579,
                'area' => 4_986,
                'visited' => true,
            ],
            [
                'id' => 41,
                'name' => '佐賀県',
                'capital' => '佐賀市',
                'population' => 820_159,
                'area' => 2_439,
                'visited' => false,
            ],
            [
                'id' => 42,
                'name' => '長崎県',
                'capital' => '長崎市',
                'population' => 1_324_078,
                'area' => 4_132,
                'visited' => false,
            ],
            [
                'id' => 43,
                'name' => '熊本県',
                'capital' => '熊本市',
                'population' => 1_748_134,
                'area' => 7_407,
                'visited' => false,
            ],
            [
                'id' => 44,
                'name' => '大分県',
                'capital' => '大分市',
                'population' => 1_121_592,
                'area' => 6_341,
                'visited' => false,
            ],
            [
                'id' => 45,
                'name' => '宮崎県',
                'capital' => '宮崎市',
                'population' => 1_061_032,
                'area' => 7_735,
                'visited' => true,
            ],
            [
                'id' => 46,
                'name' => '鹿児島県',
                'capital' => '鹿児島市',
                'population' => 1_574_625,
                'area' => 9_187,
                'visited' => true,
            ],
            [
                'id' => 47,
                'name' => '沖縄県',
                'capital' => '那覇市',
                'population' => 1_455_804,
                'area' => 2_271,
                'visited' => false,
            ],
        ];
        foreach ($prefectures as $prefecture) {
            \App\Models\Prefecture::updateOrCreate(['id' => $prefecture['id']], $prefecture);
        }
    }
}
